### ISSUE TITLE
페이스북 로그인 구현하려면 페이스북 앱이 필요합니다.

### ISSUE THREAD

**Issue by MinHyeok90** [Bokbut/bokbut#11]
https://developers.facebook.com/ 에서 
https://developers.facebook.com/quickstarts/?platform=web 를 통해 웹 페이지용 앱을 하나 만들면
해당 앱의 ID 값을 이용해 자바스크립트 sdk로 손쉽게 로그인 구현이 가능합니다.
~~devise를 이용한 페이스북 로그인 구현은 실패.. 이것도 어짜피 앱은 만들어야 함~~

따라서, 누군가 페이스북 개발자로 웹 페이지용 앱을 만들어서 키를 얻어야 합니다.
책임자를 누구로 할까요?

**Comment by gnujoow** [comment]
@likelion-minhyeok 님이 하시는걸로 해주세요 :+1:
